### RETURN VALUES ###
EXIT_OK = 0
EXIT_FAILURE = 1

###  BCPD OPTIONS ###
BCPD_MODE_KEY = "mode"
BCPD_OUTLIER_PROBABILITY_KEY = "w"
BCPD_DVL_KEY = "l"
BCPD_SMOOTH_RANGE_KEY = "b"
BCPD_POINT_MATCHING_RANDOMNESS_KEY = "g"
BCPD_MIXING_RANDOMNESS_KEY = "k"

