name: Create and publish pre-release 

on:
  push:
    branches: ['develop', 'cicd']


jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse current version
        run: echo "VERSION=$(cat SlicerBoneMorphing/SlicerBoneMorphing.py | grep Version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          cd src
          zip -r SlicerBoneMorphing-$VERSION.zip ./*
          cp SlicerBoneMorphing-$VERSION.zip ../

      - name: Create a pre-release
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN with write permissions
          script: |
            const version = process.env.VERSION;
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: v0.2.0-rc.2,
              name: version,
              body: `Release version ${version}`,
              draft: false,
              prerelease: true
            });
            return response.data.upload_url;

      - name: Upload ZIP to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./my-archive.zip
          asset_name: my-archive.zip
          asset_content_type: application/zip
