name: Create and publish pre-release 

on:
  push:
    branches: ['develop', 'cicd']


jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse current version
        run: echo "VERSION=$(cat SlicerBoneMorphing/SlicerBoneMorphing.py | grep Version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          cd src
          zip -r SlicerBoneMorphing-$VERSION.zip ./*
          cp SlicerBoneMorphing-$VERSION.zip ../

      - name: Create a pre-release link
        id: create_release_link
        uses: ncipollo/release-action@v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: SlicerBoneMorphing-$VERSION.zip
          commit: $GITHUB_REF
          bodyFile: CHANGELOG.md
          prerelease: true
          name: $VERSION

